[package]
name = "mtv_gstreamer"
version = "0.1.0"
edition = "2021"

[dependencies]
rdev = "0.5.3"
gst = { package = "gstreamer", git = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs", features = ["v1_20"] }
